# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vesshelm < Formula
  desc "Vesshelm is a CLI tool for managing Helm charts."
  homepage "https://github.com/deimosfr/vesshelm"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deimosfr/vesshelm/releases/download/v1.1.0/vesshelm_1.1.0_darwin_amd64.tar.gz"
      sha256 "54f2e006cef4d22fda838722f6390bbfa3d49ec63959c879f1c5aeab68928ae3"

      def install
        bin.install "vesshelm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deimosfr/vesshelm/releases/download/v1.1.0/vesshelm_1.1.0_darwin_arm64.tar.gz"
      sha256 "fe1f525b2686312c0db3285221e88caecec3ed5ab90634a606fcc1771426488d"

      def install
        bin.install "vesshelm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deimosfr/vesshelm/releases/download/v1.1.0/vesshelm_1.1.0_linux_amd64.tar.gz"
      sha256 "badd23771711aacf47b2c4c790ae12a73306c2bafe3468e80d255b2a275a6da7"
      def install
        bin.install "vesshelm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deimosfr/vesshelm/releases/download/v1.1.0/vesshelm_1.1.0_linux_arm64.tar.gz"
      sha256 "ac6052c1402401c13af63b6de7a49a9dae3a56aea5b9e7962dc9fa30024aa57d"
      def install
        bin.install "vesshelm"
      end
    end
  end
end
