# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vessel < Formula
  desc "Vessel is a CLI tool for managing Helm charts."
  homepage "https://github.com/deimosfr/Vessel"
  version "1.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deimosfr/vessel/releases/download/v1.2.2/vessel_1.2.2_darwin_amd64.tar.gz"
      sha256 "6cace7c4515f03b27886899d736210b72138899db169f4a71d1aa85a1f8dc613"

      def install
        bin.install "vessel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deimosfr/vessel/releases/download/v1.2.2/vessel_1.2.2_darwin_arm64.tar.gz"
      sha256 "3bd1e36d4e561f035e92642a7a620c3c9fc823b942eb33d6bb20c951570f113e"

      def install
        bin.install "vessel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deimosfr/vessel/releases/download/v1.2.2/vessel_1.2.2_linux_amd64.tar.gz"
      sha256 "e0f82958b18da53551bca72c88ed1640aaef4bc87acd17d66d3d8aebc3c3d8a9"
      def install
        bin.install "vessel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deimosfr/vessel/releases/download/v1.2.2/vessel_1.2.2_linux_arm64.tar.gz"
      sha256 "aaca128c8b3af83d0215929c68a1dc1308d445cceba387659c5adf64a41678d3"
      def install
        bin.install "vessel"
      end
    end
  end
end
