# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vesshelm < Formula
  desc "Vesshelm is a CLI tool for managing Helm charts."
  homepage "https://github.com/deimosfr/vesshelm"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deimosfr/vesshelm/releases/download/v1.3.0/vesshelm_1.3.0_darwin_amd64.tar.gz"
      sha256 "fe45e2e4a8b960b2ae447f9e3103f41db89b66814c6a6120ca38f26149861bf0"

      def install
        bin.install "vesshelm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deimosfr/vesshelm/releases/download/v1.3.0/vesshelm_1.3.0_darwin_arm64.tar.gz"
      sha256 "be7281123fde61d56d6dc9ed9e8eacabce52544668503af31d4ba42837d8f4dc"

      def install
        bin.install "vesshelm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deimosfr/vesshelm/releases/download/v1.3.0/vesshelm_1.3.0_linux_amd64.tar.gz"
      sha256 "0ad77034c2aa274afafc439e8e74d7dbb7767d26b5323adf54e594fb76a08f3f"
      def install
        bin.install "vesshelm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deimosfr/vesshelm/releases/download/v1.3.0/vesshelm_1.3.0_linux_arm64.tar.gz"
      sha256 "c4282e74ef9e788681d0a191f299c12b2fd26619fae7650dbfe24afcae938e7c"
      def install
        bin.install "vesshelm"
      end
    end
  end
end
