# This file was generated by GoReleaser. DO NOT EDIT.
cask "vessel" do
  name "vessel"
  desc "Vessel is a CLI tool for managing Helm charts."
  homepage "https://github.com/deimosfr/Vessel"
  version "1.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vessel"

  on_macos do
    on_intel do
      url "https://github.com/deimosfr/vessel/releases/download/v#{version}/vessel_#{version}_darwin_amd64.tar.gz"
      sha256 "9c6549094160c55681e3e4114ad23fb61c0c4b09aa41f20799a1b89331d1e881"
    end
    on_arm do
      url "https://github.com/deimosfr/vessel/releases/download/v#{version}/vessel_#{version}_darwin_arm64.tar.gz"
      sha256 "510ba445b4ae2f2e462b15126e3306a100a7f06556de2cc71eff33cb1cb1a32a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/deimosfr/vessel/releases/download/v#{version}/vessel_#{version}_linux_amd64.tar.gz"
      sha256 "1527d03ad41ec5460fd84e2ecc48abff3b5c5e35cade1f9708dc82159a248745"
    end
    on_arm do
      url "https://github.com/deimosfr/vessel/releases/download/v#{version}/vessel_#{version}_linux_arm64.tar.gz"
      sha256 "562c5bbe918fa060c3d398391f911635294968afe35c00b9fd01eb0e1269ef58"
    end
  end

  # No zap stanza required
end
