# This file was generated by GoReleaser. DO NOT EDIT.
cask "vessel" do
  name "vessel"
  desc "Vessel is a CLI tool for managing Helm charts."
  homepage "https://github.com/deimosfr/Vessel"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vessel"

  on_macos do
    on_intel do
      url "https://github.com/deimosfr/vessel/releases/download/v#{version}/vessel_#{version}_darwin_amd64.tar.gz"
      sha256 "00086389026e5ca63d0b05a16387b48ef7fa9702e28e6810c36c2130b16fe14c"
    end
    on_arm do
      url "https://github.com/deimosfr/vessel/releases/download/v#{version}/vessel_#{version}_darwin_arm64.tar.gz"
      sha256 "7d4c1627b7374d7920f02283078d274557ca6bc5e0adacef71e770f6c69ecb17"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/deimosfr/vessel/releases/download/v#{version}/vessel_#{version}_linux_amd64.tar.gz"
      sha256 "b60deb56e7c8a87d8aff7c84e8b2f874f873680c973f22c45e1500744400fb7a"
    end
    on_arm do
      url "https://github.com/deimosfr/vessel/releases/download/v#{version}/vessel_#{version}_linux_arm64.tar.gz"
      sha256 "90f1437180c4876a1bf4764a40c9902c6cd4146a3f933890738c953d636756cc"
    end
  end

  # No zap stanza required
end
