# This file was generated by GoReleaser. DO NOT EDIT.
cask "vessel" do
  name "vessel"
  desc "Vessel is a CLI tool for managing Helm charts."
  homepage "https://github.com/deimosfr/Vessel"
  version "1.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vessel"

  on_macos do
    on_intel do
      url "https://github.com/deimosfr/vessel/releases/download/v#{version}/vessel_#{version}_darwin_amd64.tar.gz"
      sha256 "8e0958a7e2657a6f65eefc04c17e6883257d6e0e089205ec64bbe6e7b42a3066"
    end
    on_arm do
      url "https://github.com/deimosfr/vessel/releases/download/v#{version}/vessel_#{version}_darwin_arm64.tar.gz"
      sha256 "c4c4662bebafe5ac259936279ad04dc122dbb32035971dec5e2ba3f503ffda81"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/deimosfr/vessel/releases/download/v#{version}/vessel_#{version}_linux_amd64.tar.gz"
      sha256 "4ae789fa6ddfefaea00e908c45f956a977f73dcfb20e6d01638a60aa32f4ecab"
    end
    on_arm do
      url "https://github.com/deimosfr/vessel/releases/download/v#{version}/vessel_#{version}_linux_arm64.tar.gz"
      sha256 "9e9884fb61dbe6773c115efce2317696ad42eb8da0472f10c50c46490aeb0e57"
    end
  end

  # No zap stanza required
end
